vo=gpu
hwdec=auto
gpu-context=wayland

# Subtitles
sub-auto=fuzzy
sub-font="Noto Sans"
sub-font-size=42

# OSD
osd-font="Noto Sans"
osd-font-size=32

# Audio
audio-pitch-correction=yes

# Screenshots
screenshot-format=png
screenshot-directory=~/Pictures/Screenshots
screenshot-template="%F_%P"

# Misc
keep-open=yes
save-position-on-quit=yes
